# Generated by Django 2.2.6 on 2019-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='place',
            field=models.CharField(default='', max_length=200, verbose_name='請寫下工作地點'),
        ),
        migrations.AddField(
            model_name='work',
            name='thing',
            field=models.CharField(default='', max_length=200),
        ),
    ]
