# Generated by Django 2.2.6 on 2019-10-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20191014_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='id_num',
        ),
    ]
