# Generated by Django 2.2.6 on 2019-10-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_remove_work_id_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date1',
            field=models.DateField(verbose_name='施工日期'),
        ),
    ]
