# Generated by Django 2.2.6 on 2019-10-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20191014_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date1',
            field=models.DateField(verbose_name='用工日期'),
        ),
        migrations.AlterField(
            model_name='work',
            name='place',
            field=models.CharField(default='', max_length=200, verbose_name='用工地點'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thing',
            field=models.CharField(default='', max_length=200, verbose_name='施工內容'),
        ),
        migrations.AlterField(
            model_name='work',
            name='worker',
            field=models.IntegerField(verbose_name='工人數'),
        ),
    ]
