# Generated by Django 2.2.6 on 2019-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20191014_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='worker',
            field=models.IntegerField(verbose_name='工人編號'),
        ),
    ]
