# Generated by Django 2.2.6 on 2019-10-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_auto_20191014_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='thing',
            field=models.CharField(default='', max_length=200, verbose_name='工作內容'),
        ),
    ]
