# Generated by Django 2.2.6 on 2019-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_auto_20191014_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(verbose_name='用工日期')),
                ('place', models.CharField(default='', max_length=200, verbose_name='用工地點')),
            ],
        ),
    ]
